// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default (req, res) => {
  res.statusCode = 200;
  res.json({
    data: [
      {
        id: 31,
        name: "UK Tree Planting",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:23.020Z",
        created_at: "2021-01-21T20:48:23.023Z",
        updated_at: "2021-01-21T20:48:23.023Z",
        project_continent: ["Europe"],
        company: "Carbon Footprint",
        credit_cost: 18.18,
        cert_authority: "QAS Certified, Verified Carbon Standard",
        company_location: "Basingstoke, UK",
        project_locations: ["UK"],
        project_page_link: "https://www.carbonfootprint.com/plantingtrees.html",
      },
      {
        id: 6,
        name: "Global Reforestation",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T19:21:20.054Z",
        created_at: "2021-01-21T19:21:20.057Z",
        updated_at: "2021-01-21T19:21:20.057Z",
        project_continent: ["Africa", "South America"],
        company: "Pachama",
        credit_cost: 13.2,
        cert_authority: "Verified Carbon Standard",
        company_location: "San Francisco, USA",
        project_locations: ["Brazil", "Uganda"],
        project_page_link: "https://pachama.com/explorer/bundles/reforestation",
      },
      {
        id: 7,
        name: "Tech-enabled rainforest protection",
        project_type_detailed: "REDD+",
        project_type: "reforestation",
        published_at: "2021-01-21T19:21:20.375Z",
        created_at: "2021-01-21T19:21:20.378Z",
        updated_at: "2021-01-21T19:21:20.378Z",
        project_continent: ["South America"],
        company: "Wren",
        credit_cost: 14.89,
        cert_authority: "Self-assessed",
        company_location: "San Jose, USA",
        project_locations: ["Peru"],
        project_page_link:
          "https://www.wren.co/projects/tech-enabled-rainforest-protection",
      },
      {
        id: 8,
        name: "Clean cooking fuel for refugees",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T19:21:20.624Z",
        created_at: "2021-01-21T19:21:20.628Z",
        updated_at: "2021-01-21T19:21:20.628Z",
        project_continent: ["Africa"],
        company: "Wren",
        credit_cost: 16,
        cert_authority: "Gold Standard",
        company_location: "San Jose, USA",
        project_locations: ["Uganda"],
        project_page_link: "https://www.wren.co/projects/clean-cooking-fuel",
      },
      {
        id: 9,
        name: "Regenerative agroforestry",
        project_type_detailed: "Agroforestry",
        project_type: "reforestation",
        published_at: "2021-01-21T19:21:20.773Z",
        created_at: "2021-01-21T19:21:20.776Z",
        updated_at: "2021-01-21T19:21:20.776Z",
        project_continent: ["Europe"],
        company: "Wren",
        credit_cost: 31.25,
        cert_authority: "Self-assessed",
        company_location: "San Jose, USA",
        project_locations: ["Scotland"],
        project_page_link:
          "https://www.wren.co/projects/regenerative-agroforestry",
      },
      {
        id: 10,
        name: "Community tree planting",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T19:21:20.927Z",
        created_at: "2021-01-21T19:21:20.930Z",
        updated_at: "2021-01-21T19:21:20.930Z",
        project_continent: ["Africa"],
        company: "Wren",
        credit_cost: 12.5,
        cert_authority: "Verified Carbon Standard",
        company_location: "San Jose, USA",
        project_locations: ["Kenya", "Tanzania", "Uganda"],
        project_page_link:
          "https://www.wren.co/projects/community-tree-planting",
      },
      {
        id: 11,
        name: "The Wren Climate Fund",
        project_type_detailed:
          "Agroforestry, Alternative Cooking, REDD+, Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T19:21:21.328Z",
        created_at: "2021-01-21T19:21:21.331Z",
        updated_at: "2021-01-21T19:21:21.331Z",
        project_continent: ["Africa", "Europe", "South America"],
        company: "Wren",
        credit_cost: 18,
        cert_authority:
          "American Carbon Registry, Gold Standard, Self-assessed",
        company_location: "San Jose, USA",
        project_locations: ["Kenya", "Peru", "Scotland", "Tanzania", "Uganda"],
        project_page_link: "https://www.wren.co/portfolios/wren-climate-fund",
      },
      {
        id: 19,
        name: "Kenya Burn Stoves Project",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T20:48:16.423Z",
        created_at: "2021-01-21T20:48:16.428Z",
        updated_at: "2021-01-21T20:48:16.428Z",
        project_continent: ["Africa"],
        company: "Carbonfund.org",
        credit_cost: 10,
        cert_authority: "Gold Standard",
        company_location: "New York, USA",
        project_locations: ["Kenya"],
        project_page_link:
          "https://carbonfund.org/project/kenya-burn-stoves-project/",
      },
      {
        id: 20,
        name: "Waste Energy Co-Generation",
        project_type_detailed: "Energy Efficiency",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:16.783Z",
        created_at: "2021-01-21T20:48:16.793Z",
        updated_at: "2021-01-21T20:48:16.793Z",
        project_continent: ["Asia"],
        company: "Carbonfund.org",
        credit_cost: 10,
        cert_authority: "Verified Carbon Standard",
        company_location: "New York, USA",
        project_locations: ["South Korea"],
        project_page_link:
          "https://carbonfund.org/project/the-south-korea-waste-energy-co-generation/",
      },
      {
        id: 21,
        name: "Aqua Clara Water Filtration Programme",
        project_type_detailed: "Water",
        project_type: "social",
        published_at: "2021-01-21T20:48:16.999Z",
        created_at: "2021-01-21T20:48:17.002Z",
        updated_at: "2021-01-21T20:48:17.002Z",
        project_continent: ["Africa"],
        company: "Carbonfund.org",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "New York, USA",
        project_locations: ["Kenya"],
        project_page_link:
          "https://carbonfund.org/project/the-aqua-clara-water-filtration-programme/",
      },
      {
        id: 22,
        name: "Truck Stop Electrification",
        project_type_detailed: "Transport",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:17.437Z",
        created_at: "2021-01-21T20:48:17.442Z",
        updated_at: "2021-01-21T20:48:17.442Z",
        project_continent: ["North America"],
        company: "Carbonfund.org",
        credit_cost: 10,
        cert_authority: "American Carbon Registry",
        company_location: "New York, USA",
        project_locations: ["USA"],
        project_page_link:
          "https://carbonfund.org/project/truck-stop-electrification/",
      },
      {
        id: 23,
        name: "Soma III Wind Farm",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:18.119Z",
        created_at: "2021-01-21T20:48:18.122Z",
        updated_at: "2021-01-21T20:48:18.122Z",
        project_continent: ["Europe"],
        company: "Carbonfund.org",
        credit_cost: 10,
        cert_authority: "Gold Standard",
        company_location: "New York, USA",
        project_locations: ["Turkey"],
        project_page_link:
          "https://carbonfund.org/project/soma-iii-wind-farm-project/",
      },
      {
        id: 24,
        name: "Gujarat Solar Power Plant",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:18.414Z",
        created_at: "2021-01-21T20:48:18.416Z",
        updated_at: "2021-01-21T20:48:18.416Z",
        project_continent: ["Asia"],
        company: "Carbonfund.org",
        credit_cost: 10,
        cert_authority: "Verified Carbon Standard",
        company_location: "New York, USA",
        project_locations: ["India"],
        project_page_link:
          "https://carbonfund.org/project/15-mw-solar-power-plant-of-gujarat/",
      },
      {
        id: 25,
        name: "Landfill Gas to Energy Project",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:18.830Z",
        created_at: "2021-01-21T20:48:18.833Z",
        updated_at: "2021-01-21T20:48:18.833Z",
        project_continent: ["North America"],
        company: "Carbonfund.org",
        credit_cost: 10,
        cert_authority: "Verified Carbon Standard",
        company_location: "New York, USA",
        project_locations: ["USA"],
        project_page_link:
          "https://carbonfund.org/project/new-bedford-landfill-gas-to-energy-project/",
      },
      {
        id: 26,
        name: "Genesis Forest",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:19.163Z",
        created_at: "2021-01-21T20:48:19.165Z",
        updated_at: "2021-01-21T20:48:19.165Z",
        project_continent: ["Europe"],
        company: "Reforestum",
        credit_cost: 20.42,
        cert_authority: "Self-assessed",
        company_location: "Spain, Valladolid",
        project_locations: ["Spain"],
        project_page_link: "https://app.reforestum.com/my-forests/1/about",
      },
      {
        id: 27,
        name: "Cordillera Azul",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:20.177Z",
        created_at: "2021-01-21T20:48:20.181Z",
        updated_at: "2021-01-21T20:48:20.181Z",
        project_continent: ["South America"],
        company: "Reforestum",
        credit_cost: 11.43,
        cert_authority: "Verified Carbon Standard",
        company_location: "Spain, Valladolid",
        project_locations: ["Peru"],
        project_page_link: "https://app.reforestum.com/my-forests/3/about",
      },
      {
        id: 28,
        name: "Sumatra Merang Peatland",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:20.782Z",
        created_at: "2021-01-21T20:48:20.785Z",
        updated_at: "2021-01-21T20:48:20.785Z",
        project_continent: ["Asia"],
        company: " Reforestum",
        credit_cost: 11.43,
        cert_authority: "Verified Carbon Standard",
        company_location: "Spain, Valladolid",
        project_locations: ["Indonesia"],
        project_page_link: "https://app.reforestum.com/my-forests/2/about",
      },
      {
        id: 29,
        name: "Ecologi Portfolio",
        project_type_detailed: "Multiple",
        project_type: "mixed",
        published_at: "2021-01-21T20:48:21.266Z",
        created_at: "2021-01-21T20:48:21.268Z",
        updated_at: "2021-01-21T20:48:21.268Z",
        project_continent: [
          "Europe",
          "Africa",
          "North America",
          "South America",
          "Asia",
        ],
        company: "Ecologi",
        credit_cost: 6.82,
        cert_authority: "Gold Standard",
        company_location: "Andover, UK",
        project_locations: ["Multiple"],
        project_page_link: "https://ecologi.com/projects",
      },
      {
        id: 30,
        name: "Global Alternative Energy Portfolio",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:22.007Z",
        created_at: "2021-01-21T20:48:22.010Z",
        updated_at: "2021-01-21T20:48:22.010Z",
        project_continent: ["Asia"],
        company: "Carbon Footprint",
        credit_cost: 8.46,
        cert_authority: "QAS Certified, Verified Carbon Standard",
        company_location: "Basingstoke, UK",
        project_locations: ["China", "India", "Phillipines"],
        project_page_link:
          "https://www.carbonfootprint.com/offsetalternativeenergy.html",
      },
      {
        id: 32,
        name: "Kenya Reforestation",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:23.845Z",
        created_at: "2021-01-21T20:48:23.856Z",
        updated_at: "2021-01-21T20:48:23.856Z",
        project_continent: ["Africa"],
        company: "Carbon Footprint",
        credit_cost: 13.39,
        cert_authority: "QAS Certified, Verified Carbon Standard",
        company_location: "Basingstoke, UK",
        project_locations: ["Kenya"],
        project_page_link:
          "https://www.carbonfootprint.com/plantingtreesinkenya.html",
      },
      {
        id: 33,
        name: "Americas Offsetting",
        project_type_detailed: "Reforestation, Renewable Energy",
        project_type: "mixed",
        published_at: "2021-01-21T20:48:24.442Z",
        created_at: "2021-01-21T20:48:24.447Z",
        updated_at: "2021-01-21T20:48:24.447Z",
        project_continent: ["South America"],
        company: "Carbon Footprint",
        credit_cost: 9.86,
        cert_authority: "QAS Certified, Verified Carbon Standard",
        company_location: "Basingstoke, UK",
        project_locations: ["Brazil", "Chile", "Uruguay"],
        project_page_link:
          "https://www.carbonfootprint.com/americas_offsets.html",
      },
      {
        id: 34,
        name: "Gold Standard Carbon Offsetting",
        project_type_detailed: "Alternative Cooking, Water",
        project_type: "social",
        published_at: "2021-01-21T20:48:24.687Z",
        created_at: "2021-01-21T20:48:24.690Z",
        updated_at: "2021-01-21T20:48:24.690Z",
        project_continent: ["Asia", "Africa"],
        company: "Carbon Footprint",
        credit_cost: 11.27,
        cert_authority: "Gold Standard, QAS Certified",
        company_location: "Basingstoke, UK",
        project_locations: ["China", "India", "Uganda"],
        project_page_link:
          "https://www.carbonfootprint.com/offsetprojects.html",
      },
      {
        id: 35,
        name: "Forest Carbon UK",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:25.256Z",
        created_at: "2021-01-21T20:48:25.259Z",
        updated_at: "2021-01-21T20:48:25.259Z",
        project_continent: ["Europe"],
        company: "Forest Carbon",
        credit_cost: 13.61,
        cert_authority: "UK Woodland Carbon Code",
        company_location: "Durham, UK",
        project_locations: ["UK"],
        project_page_link: "https://www.forestcarbon.co.uk/single-credits",
      },
      {
        id: 36,
        name: "Safe Water Access in Rwanda",
        project_type_detailed: "Water",
        project_type: "social",
        published_at: "2021-01-21T20:48:26.133Z",
        created_at: "2021-01-21T20:48:26.136Z",
        updated_at: "2021-01-21T20:48:26.136Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 12,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Rwanda"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/safe-water-access-rwanda",
      },
      {
        id: 37,
        name: "Cleaner Cook Stoves in Rwanda",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T20:48:27.561Z",
        created_at: "2021-01-21T20:48:27.584Z",
        updated_at: "2021-01-21T20:48:27.584Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Rwanda"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/cleaner-cook-stoves-rwanda",
      },
      {
        id: 38,
        name:
          "Efficient and Clean Cooking for Mozambican Low-Income Households",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T20:48:27.880Z",
        created_at: "2021-01-21T20:48:27.883Z",
        updated_at: "2021-01-21T20:48:27.883Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 18,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Mozambique"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/efficient-clean-cooking-mozambican-low-income-households",
      },
      {
        id: 39,
        name: "Cleaner and Safer Stoves in Malawi",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T20:48:28.472Z",
        created_at: "2021-01-21T20:48:28.475Z",
        updated_at: "2021-01-21T20:48:28.475Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Malawi"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/cleaner-and-safer-stoves-malawi",
      },
      {
        id: 40,
        name: "Wind Power Project in Andhra Pradesh",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:29.213Z",
        created_at: "2021-01-21T20:48:29.223Z",
        updated_at: "2021-01-21T20:48:29.223Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 10,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["India"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/100-mw-wind-power-project-anantapur-andhra-pradesh",
      },
      {
        id: 41,
        name: "Sidrap Wind Farm Project",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:29.501Z",
        created_at: "2021-01-21T20:48:29.513Z",
        updated_at: "2021-01-21T20:48:29.513Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 10,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Indonesia"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/sidrap-wind-farm-project-indonesia",
      },
      {
        id: 42,
        name: "Planting Biodiverse Forests",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:29.649Z",
        created_at: "2021-01-21T20:48:29.657Z",
        updated_at: "2021-01-21T20:48:29.657Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 18,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Panama"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/planting-biodiverse-forests-panama",
      },
      {
        id: 43,
        name: "Ceará Renewable Energy Project",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:29.800Z",
        created_at: "2021-01-21T20:48:29.803Z",
        updated_at: "2021-01-21T20:48:29.803Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 11,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Brazil"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/ceara-renewable-energy-bundled-project",
      },
      {
        id: 44,
        name: "Solar Power Project by Arhyama Solar Power",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:29.930Z",
        created_at: "2021-01-21T20:48:29.933Z",
        updated_at: "2021-01-21T20:48:29.933Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 12,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["India"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/6mw-solar-power-project-arhyama-solar-power",
      },
      {
        id: 45,
        name: "Utsil Naj - healthy homes for all",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T20:48:30.519Z",
        created_at: "2021-01-21T20:48:30.522Z",
        updated_at: "2021-01-21T20:48:30.522Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 18,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Guatemala"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/utsil-naj-healthy-homes-guatemala",
      },
      {
        id: 46,
        name: "Nicaforest High Impact Reforestation Program",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-21T20:48:31.007Z",
        created_at: "2021-01-21T20:48:31.010Z",
        updated_at: "2021-01-21T20:48:31.010Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 34,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Nicuragua"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/nicaforest-high-impact-reforestation-program",
      },
      {
        id: 47,
        name: "Biomass Power Project in Chhattisgarh",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-21T20:48:31.648Z",
        created_at: "2021-01-21T20:48:31.652Z",
        updated_at: "2021-01-21T20:48:31.652Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 11,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["India"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/20-mw-biomass-power-project-chhattisgarh-india",
      },
      {
        id: 48,
        name: "Solar Cooking for Refugee Families",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T20:48:32.190Z",
        created_at: "2021-01-21T20:48:32.200Z",
        updated_at: "2021-01-21T20:48:32.200Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Chad"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/solar-cooking-refugee-families-chad",
      },
      {
        id: 49,
        name: "Myanmar Stoves Campaign",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-21T20:48:32.667Z",
        created_at: "2021-01-21T20:48:32.670Z",
        updated_at: "2021-01-21T20:48:32.670Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Myanmar"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/myanmar-stoves-campaign",
      },
      {
        id: 50,
        name: "Fairtrade Project: Cookstoves for coffee farmers",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:21.115Z",
        created_at: "2021-01-22T13:14:21.126Z",
        updated_at: "2021-01-22T13:14:21.126Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 22,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Ethiopia"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/fairtrade-project-cookstoves-coffee-farmers-ethiopia",
      },
      {
        id: 51,
        name: "Wind Power Project in Rajasthan",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-22T13:14:21.332Z",
        created_at: "2021-01-22T13:14:21.337Z",
        updated_at: "2021-01-22T13:14:21.337Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 10,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["India"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/225-mw-wind-power-project-rajasthan-india",
      },
      {
        id: 52,
        name: "Improved Cookstoves",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:21.733Z",
        created_at: "2021-01-22T13:14:21.758Z",
        updated_at: "2021-01-22T13:14:21.758Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 20,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Guinea"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/improved-cookstoves-guinea",
      },
      {
        id: 53,
        name: "Utsil Naj - healthy homes for all in Mexico",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:22.026Z",
        created_at: "2021-01-22T13:14:22.033Z",
        updated_at: "2021-01-22T13:14:22.033Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 18,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Mexico"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/utsil-naj-healthy-homes-mexico",
      },
      {
        id: 54,
        name: "Kenya Biogas Programme",
        project_type_detailed: "Alternative Cooking",
        project_type: "renewables",
        published_at: "2021-01-22T13:14:22.407Z",
        created_at: "2021-01-22T13:14:22.413Z",
        updated_at: "2021-01-22T13:14:22.413Z",
        project_continent: ["Africa"],
        company: "Gold Standard",
        credit_cost: 19,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Kenya"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/kenya-biogas-programme",
      },
      {
        id: 55,
        name: "More Efficient Cooking and Heating in China",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:22.658Z",
        created_at: "2021-01-22T13:14:22.664Z",
        updated_at: "2021-01-22T13:14:22.664Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["China"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/more-efficient-cooking-and-heating-china",
      },
      {
        id: 56,
        name: "Emissions Reductions from PET Recycling",
        project_type_detailed: "Waste Management",
        project_type: "social",
        published_at: "2021-01-22T13:14:23.078Z",
        created_at: "2021-01-22T13:14:23.082Z",
        updated_at: "2021-01-22T13:14:23.082Z",
        project_continent: ["Europe"],
        company: "Gold Standard",
        credit_cost: 47,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Romania"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/plastic-recycling-romania-europe",
      },
      {
        id: 57,
        name: "Fairtrade Project: Improved cookstoves for women",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:23.297Z",
        created_at: "2021-01-22T13:14:23.307Z",
        updated_at: "2021-01-22T13:14:23.307Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 19,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["India"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/fairtrade-project-improved-cookstoves-women-india",
      },
      {
        id: 58,
        name: "Terraclear - Clean water access for families",
        project_type_detailed: "Water",
        project_type: "social",
        published_at: "2021-01-22T13:14:23.670Z",
        created_at: "2021-01-22T13:14:23.681Z",
        updated_at: "2021-01-22T13:14:23.681Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Laos"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/terraclear-clean-water-access-families-laos",
      },
      {
        id: 59,
        name: "Utsil Naj - healthy homes for all in Honduras",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:23.900Z",
        created_at: "2021-01-22T13:14:23.903Z",
        updated_at: "2021-01-22T13:14:23.903Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 25,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Honduras"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/utsil-naj-healthy-homes-all-honduras",
      },
      {
        id: 60,
        name: "Betulia Hydroelectric Project",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-22T13:14:24.264Z",
        created_at: "2021-01-22T13:14:24.275Z",
        updated_at: "2021-01-22T13:14:24.275Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Honduras"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/betulia-hydroelectric-project-honduras",
      },
      {
        id: 62,
        name: "Qori Q’oncha Improved Cookstoves",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:25.199Z",
        created_at: "2021-01-22T13:14:25.202Z",
        updated_at: "2021-01-22T13:14:25.202Z",
        project_continent: ["South America"],
        company: "Gold Standard",
        credit_cost: 15,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Peru"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/qori-q-oncha-improved-cookstoves-diffusion-programme-peru",
      },
      {
        id: 63,
        name: "WithOneSeed Community Forest Programme",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-22T13:14:25.338Z",
        created_at: "2021-01-22T13:14:25.341Z",
        updated_at: "2021-01-22T13:14:25.341Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 18,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Timor"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/withoneseed-timor-leste-community-forestry-programme",
      },
      {
        id: 64,
        name: "Wind Power Project in Madhya Pradesh",
        project_type_detailed: "Renewable Energy",
        project_type: "renewables",
        published_at: "2021-01-22T13:14:25.728Z",
        created_at: "2021-01-22T13:14:25.735Z",
        updated_at: "2021-01-22T13:14:25.735Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 10,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["India"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/1005-mw-wind-project-india-orange-renewable",
      },
      {
        id: 65,
        name: "My Carbon Plan",
        project_type_detailed: "Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-22T13:14:25.947Z",
        created_at: "2021-01-22T13:14:25.954Z",
        updated_at: "2021-01-22T13:14:25.954Z",
        project_continent: ["Europe"],
        company: "MyCarbonPlan",
        credit_cost: 8.89,
        cert_authority: "UK Woodland Carbon Code",
        company_location: "Hertfordshire",
        project_locations: ["UK"],
        project_page_link: "https://www.mycarbonplan.org/",
      },
      {
        id: 66,
        name: "C-Level Project Portfolio",
        project_type_detailed: "Protect Deforestation, Reforestation",
        project_type: "mixed",
        published_at: "2021-01-22T13:14:26.163Z",
        created_at: "2021-01-22T13:14:26.167Z",
        updated_at: "2021-01-22T13:14:26.167Z",
        project_continent: ["Africa", "South America", "Asia"],
        company: "Clevel",
        credit_cost: 20.39,
        cert_authority: "Plan Vivo Standard",
        company_location: "Brighton",
        project_locations: [
          "Kenya",
          "Meghalaya",
          "Mexico",
          "Mongolia",
          "Uganda",
        ],
        project_page_link:
          "https://www.clevel.co.uk/offset-a-desired-amount-of-co2/",
      },
      {
        id: 67,
        name: "ClimateCare Portfolio",
        project_type_detailed: "Protect Deforestation, Reforestation",
        project_type: "mixed",
        published_at: "2021-01-22T13:14:26.307Z",
        created_at: "2021-01-22T13:14:26.311Z",
        updated_at: "2021-01-22T13:14:26.311Z",
        project_continent: [
          "Africa",
          "Asia",
          "North America",
          "South America",
          "Africa",
        ],
        company: "ClimateCare",
        credit_cost: 10.25,
        cert_authority: "Gold Standard",
        company_location: "Oxford",
        project_locations: ["Multiple"],
        project_page_link: "https://climatecare.org/calculator/",
      },
      {
        id: 68,
        name: "World Land Trust Land Acqusition",
        project_type_detailed: "Protect Deforestation, Reforestation",
        project_type: "reforestation",
        published_at: "2021-01-22T13:14:26.471Z",
        created_at: "2021-01-22T13:14:26.475Z",
        updated_at: "2021-01-22T13:14:26.475Z",
        project_continent: [
          "Africa",
          "Asia",
          "North America",
          "South America",
          "Africa",
        ],
        company: "Worldland Trust ",
        credit_cost: 20.53,
        cert_authority: "Self-certified",
        company_location: "Suffolk",
        project_locations: ["Multiple"],
        project_page_link:
          "https://www.worldlandtrust.org/carbon-calculator/individual/fixed/fixed-quick-offset/",
      },
      {
        id: 69,
        name: "MyClimate Portfolio",
        project_type_detailed: "Multiple",
        project_type: "mixed",
        published_at: "2021-01-22T13:14:26.799Z",
        created_at: "2021-01-22T13:14:26.808Z",
        updated_at: "2021-01-22T13:14:26.808Z",
        project_continent: ["Africa", "Asia", "South America", "Africa"],
        company: "MyClimate",
        credit_cost: 34.21,
        cert_authority: "CDM, Gold Standard, Plan Vivo Standard",
        company_location: "Switzerland",
        project_locations: ["mixed"],
        project_page_link: "https://co2.myclimate.org/en/cart",
      },
      {
        id: 70,
        name: "Clear Offset Portfolio",
        project_type_detailed: "Multiple",
        project_type: "mixed",
        published_at: "2021-01-22T13:14:27.159Z",
        created_at: "2021-01-22T13:14:27.162Z",
        updated_at: "2021-01-22T13:14:27.162Z",
        project_continent: ["Africa", "South America", "Asia"],
        company: "Clear-Offset",
        credit_cost: 20.72,
        cert_authority: "Gold Standard, QAS Certified, Redd+",
        company_location: "UK",
        project_locations: ["Amazon", "Chile", "Malawi", "Thailand", "Zambezi"],
        project_page_link:
          "https://clear-offset.com/carbon-offset-business-fuel/",
      },
      {
        id: 61,
        name: "Fairtrade Project: Clean cooking with biogas",
        project_type_detailed: "Alternative Cooking",
        project_type: "social",
        published_at: "2021-01-22T13:14:24.989Z",
        created_at: "2021-01-22T13:14:24.992Z",
        updated_at: "2021-01-22T13:19:02.807Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 22,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["India"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/fairtrade-project-clean-cooking-biogas-india",
      },
      {
        id: 73,
        name: "Cambodia National Biodigester Programme",
        project_type_detailed: "Renewable Energy",
        project_type: "social",
        published_at: "2021-01-22T13:19:14.156Z",
        created_at: "2021-01-22T13:19:14.172Z",
        updated_at: "2021-01-22T13:19:14.172Z",
        project_continent: ["Asia"],
        company: "Gold Standard",
        credit_cost: 19,
        cert_authority: "Gold Standard",
        company_location: "Geneva, Switzerland",
        project_locations: ["Cambodia"],
        project_page_link:
          "https://marketplace.goldstandard.org/collections/projects/products/cambodia-national-biodigester-programme",
      },
    ],
  });
};
